[KEYHANDLER] Fix build failure due to upstream changes
ERROR: device/jsr/d10f/keyhandler/src/com/cyanogenmod/settings/device/KeyHandler.java:16: The type KeyHandler must implement the inherited abstract method DeviceKeyHandler.handleKeyEvent(KeyEvent, DeviceKeyHandler$DeviceHandlerCallback)
Got broken by frameworks/base commit db1b4e6e4880be1828342be9bc468d36565a2ef0

Change-Id: Iea9886993f9cfd7c88b61460f9baab99c6f29976